language: go
go: 1.12.1
sudo: true # give us 7.5GB and >2 bursted cores.
git:
  depth: false
install:
    # Yarn and TS toolchain.
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
    - yarn global add tslint
    - yarn global add typescript
    - make ensure
script:
    - make travis_${TRAVIS_EVENT_TYPE}
notifications:
    webhooks: https://zlmgkhmhjc.execute-api.us-west-2.amazonaws.com/stage/travis
